#!/usr/bin/env python3

import sys
import time
import docker
import pathlib

from docker.types import Mount


python_version = f"{sys.version_info[0]}."\
	f"{sys.version_info[1]}."\
	f"{sys.version_info[2]}"

client = docker.from_env()

cont = client.containers.create(
	"pytest-vnet:netvm",
	privileged=True,
	tty=True,
	mounts=[
		# Mount(
		# 	f"/root/.pyenv/versions/{python_version}/lib/python{sys.version_info[0]}.{sys.version_info[1]}/site-packages",
		# 	str(pathlib.Path.home() / f".pyenv/versions/{python_version}/lib/python{sys.version_info[0]}.{sys.version_info[1]}/site-packages"),
		# 	"bind",
		# 	read_only=True
		# 	),
		Mount(
			"/root/test",
			str(pathlib.Path().absolute()),
			"bind",
			read_only=True
			)
		]
	)

cont.start()

_, out = cont.exec_run(
	["mn", "--test", "pingall"],
	workdir="/root/test",
	stream=True
	)

for chunk in out:
	print(chunk.decode("utf-8"), end="", flush=True)

cont.stop()
cont.remove()