#!/usr/bin/env python3

import sys
import time
import docker
import pathlib

from docker.types import Mount

client = docker.from_env()

cont = client.containers.create(
	"pytest-vnet:netvm",
	privileged=True,
	mounts=[
		Mount(
			"/root/.pyenv",
			str(pathlib.Path.home() / ".pyenv"),
			"bind"
			)
		]
	)

cont.start()

_, out = cont.exec_run(
	["python3", "-c", "import mininet\nimport sys\nprint(sys.version_info)"],
	workdir="/root"
	)

print(out.decode("utf-8"), end="", flush=True)

cont.stop()
cont.remove()